export const susenasEntriData = [
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Kinali",
    nagari: "Kinali",
    sls: "01",
    kode_sls_subsls: "0101",
    nks: "101",
    no_ruta: "001",
    nama_petugas_entri: "Renzi",
    tgl_entri: new Date("2026-01-21T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Luhak Nan Duo",
    nagari: "Simpang Empat",
    sls: "02",
    kode_sls_subsls: "0202",
    nks: "102",
    no_ruta: "002",
    nama_petugas_entri: "Renzi",
    tgl_entri: new Date("2026-01-21T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Gunung Tuleh",
    nagari: "Gunung Tuleh",
    sls: "03",
    kode_sls_subsls: "0303",
    nks: "103",
    no_ruta: "003",
    nama_petugas_entri: "Renzi",
    tgl_entri: new Date("2026-01-21T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Aur",
    nagari: "Sungai Aur",
    sls: "04",
    kode_sls_subsls: "0404",
    nks: "104",
    no_ruta: "004",
    nama_petugas_entri: "Renzi",
    tgl_entri: new Date("2026-01-21T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Talamau",
    nagari: "Talu",
    sls: "05",
    kode_sls_subsls: "0505",
    nks: "105",
    no_ruta: "005",
    nama_petugas_entri: "Renzi",
    tgl_entri: new Date("2026-01-21T17:00:00.000Z"),
  },
];

export const serutiEntriData = [
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Kinali",
    nagari: "Kinali",
    sls: "01",
    kode_sls_subsls: "0101",
    nks: "201",
    no_ruta: "001",
    nama_petugas_entri: "Andi Saputra",
    tgl_entri: new Date("2026-01-21T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Luhak Nan Duo",
    nagari: "Simpang Empat",
    sls: "02",
    kode_sls_subsls: "0201",
    nks: "202",
    no_ruta: "002",
    nama_petugas_entri: "Budi Hartono",
    tgl_entri: new Date("2026-01-22T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Gunung Tuleh",
    nagari: "Gunung Tuleh",
    sls: "03",
    kode_sls_subsls: "0301",
    nks: "203",
    no_ruta: "003",
    nama_petugas_entri: "Citra Dewi",
    tgl_entri: new Date("2026-01-23T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Aur",
    nagari: "Sungai Aur",
    sls: "04",
    kode_sls_subsls: "0401",
    nks: "204",
    no_ruta: "004",
    nama_petugas_entri: "Deni Pratama",
    tgl_entri: new Date("2026-01-24T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Talamau",
    nagari: "Talu",
    sls: "05",
    kode_sls_subsls: "0501",
    nks: "205",
    no_ruta: "005",
    nama_petugas_entri: "Eka Putri",
    tgl_entri: new Date("2026-01-25T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sasak Ranah Pasisie",
    nagari: "Sasak",
    sls: "06",
    kode_sls_subsls: "0601",
    nks: "206",
    no_ruta: "006",
    nama_petugas_entri: "Fajar Nugroho",
    tgl_entri: new Date("2026-01-26T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Pasaman",
    nagari: "Aua Kuniang",
    sls: "07",
    kode_sls_subsls: "0701",
    nks: "207",
    no_ruta: "007",
    nama_petugas_entri: "Gita Lestari",
    tgl_entri: new Date("2026-01-27T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Koto Balingka",
    nagari: "Parit",
    sls: "08",
    kode_sls_subsls: "0801",
    nks: "208",
    no_ruta: "008",
    nama_petugas_entri: "Hendra Wijaya",
    tgl_entri: new Date("2026-01-28T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Ranah Batahan",
    nagari: "Batahan",
    sls: "09",
    kode_sls_subsls: "0901",
    nks: "209",
    no_ruta: "009",
    nama_petugas_entri: "Intan Permata",
    tgl_entri: new Date("2026-01-29T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Beremas",
    nagari: "Maligi",
    sls: "10",
    kode_sls_subsls: "1001",
    nks: "210",
    no_ruta: "010",
    nama_petugas_entri: "Joko Santoso",
    tgl_entri: new Date("2026-01-30T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Lembah Melintang",
    nagari: "Ujung Gading",
    sls: "11",
    kode_sls_subsls: "1101",
    nks: "211",
    no_ruta: "011",
    nama_petugas_entri: "Kartika Sari",
    tgl_entri: new Date("2026-01-31T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Air Bangis",
    nagari: "Air Bangis",
    sls: "12",
    kode_sls_subsls: "1201",
    nks: "212",
    no_ruta: "012",
    nama_petugas_entri: "Lukman Hakim",
    tgl_entri: new Date("2026-02-01T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Kinali Selatan",
    nagari: "Anam Koto Utara",
    sls: "13",
    kode_sls_subsls: "1301",
    nks: "213",
    no_ruta: "013",
    nama_petugas_entri: "Maya Salsabila",
    tgl_entri: new Date("2026-02-02T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Talamau Utara",
    nagari: "Sinuruik",
    sls: "14",
    kode_sls_subsls: "1401",
    nks: "214",
    no_ruta: "014",
    nama_petugas_entri: "Nanda Prakoso",
    tgl_entri: new Date("2026-02-03T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Gunung Tuleh Barat",
    nagari: "Muaro Kiawai",
    sls: "15",
    kode_sls_subsls: "1501",
    nks: "215",
    no_ruta: "015",
    nama_petugas_entri: "Oki Ramadhan",
    tgl_entri: new Date("2026-02-04T17:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Aur Selatan",
    nagari: "Rabi Jonggor",
    sls: "16",
    kode_sls_subsls: "1601",
    nks: "216",
    no_ruta: "016",
    nama_petugas_entri: "Putri Anggraini",
    tgl_entri: new Date("2026-02-05T17:00:00.000Z"),
  },
];

export const susenasMasukData = [
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Kinali",
    nagari: "Kinali",
    sls: "01",
    kode_sls_subsls: "0101",
    nks: "301",
    nama_PML: "Andi Saputra",
    nama_PPL: "Rina Oktaviani",
    no_ruta: "001",
    tgl_masuk: new Date("2026-01-10T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Luhak Nan Duo",
    nagari: "Simpang Empat",
    sls: "02",
    kode_sls_subsls: "0201",
    nks: "302",
    nama_PML: "Budi Hartono",
    nama_PPL: "Sari Wulandari",
    no_ruta: "002",
    tgl_masuk: new Date("2026-01-11T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Gunung Tuleh",
    nagari: "Gunung Tuleh",
    sls: "03",
    kode_sls_subsls: "0301",
    nks: "303",
    nama_PML: "Candra Pratama",
    nama_PPL: "Dewi Anggraini",
    no_ruta: "003",
    tgl_masuk: new Date("2026-01-12T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Aur",
    nagari: "Sungai Aur",
    sls: "04",
    kode_sls_subsls: "0401",
    nks: "304",
    nama_PML: "Deni Kurniawan",
    nama_PPL: "Fitria Ningsih",
    no_ruta: "004",
    tgl_masuk: new Date("2026-01-13T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Talamau",
    nagari: "Talu",
    sls: "05",
    kode_sls_subsls: "0501",
    nks: "305",
    nama_PML: "Eko Setiawan",
    nama_PPL: "Gita Lestari",
    no_ruta: "005",
    tgl_masuk: new Date("2026-01-14T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sasak Ranah Pasisie",
    nagari: "Sasak",
    sls: "06",
    kode_sls_subsls: "0601",
    nks: "306",
    nama_PML: "Fahmi Rizal",
    nama_PPL: "Hani Putri",
    no_ruta: "006",
    tgl_masuk: new Date("2026-01-15T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Pasaman",
    nagari: "Aua Kuniang",
    sls: "07",
    kode_sls_subsls: "0701",
    nks: "307",
    nama_PML: "Gunawan Prakoso",
    nama_PPL: "Intan Maharani",
    no_ruta: "007",
    tgl_masuk: new Date("2026-01-16T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Koto Balingka",
    nagari: "Parit",
    sls: "08",
    kode_sls_subsls: "0801",
    nks: "308",
    nama_PML: "Hendra Wijaya",
    nama_PPL: "Jihan Safitri",
    no_ruta: "008",
    tgl_masuk: new Date("2026-01-17T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Ranah Batahan",
    nagari: "Batahan",
    sls: "09",
    kode_sls_subsls: "0901",
    nks: "309",
    nama_PML: "Irwan Maulana",
    nama_PPL: "Kartika Sari",
    no_ruta: "009",
    tgl_masuk: new Date("2026-01-18T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Beremas",
    nagari: "Maligi",
    sls: "10",
    kode_sls_subsls: "1001",
    nks: "310",
    nama_PML: "Joko Santoso",
    nama_PPL: "Laila Ramadhani",
    no_ruta: "010",
    tgl_masuk: new Date("2026-01-19T08:00:00.000Z"),
  },
];


export const serutiMasukData = [
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Kinali",
    nagari: "Kinali",
    sls: "01",
    kode_sls_subsls: "0102",
    nks: "401",
    nama_PML: "Agus Salim",
    nama_PPL: "Rina Oktaviani",
    no_ruta: "001",
    tgl_masuk: new Date("2026-02-01T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Luhak Nan Duo",
    nagari: "Simpang Empat",
    sls: "02",
    kode_sls_subsls: "0202",
    nks: "402",
    nama_PML: "Bambang Irawan",
    nama_PPL: "Sari Puspita",
    no_ruta: "002",
    tgl_masuk: new Date("2026-02-02T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Gunung Tuleh",
    nagari: "Gunung Tuleh",
    sls: "03",
    kode_sls_subsls: "0302",
    nks: "403",
    nama_PML: "Cahyo Nugroho",
    nama_PPL: "Dewi Larasati",
    no_ruta: "003",
    tgl_masuk: new Date("2026-02-03T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Aur",
    nagari: "Sungai Aur",
    sls: "04",
    kode_sls_subsls: "0402",
    nks: "404",
    nama_PML: "Darmawan Putra",
    nama_PPL: "Fitri Handayani",
    no_ruta: "004",
    tgl_masuk: new Date("2026-02-04T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Talamau",
    nagari: "Talu",
    sls: "05",
    kode_sls_subsls: "0502",
    nks: "405",
    nama_PML: "Edi Susanto",
    nama_PPL: "Gina Maharani",
    no_ruta: "005",
    tgl_masuk: new Date("2026-02-05T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sasak Ranah Pasisie",
    nagari: "Sasak",
    sls: "06",
    kode_sls_subsls: "0602",
    nks: "406",
    nama_PML: "Feri Kurniawan",
    nama_PPL: "Hilda Amalia",
    no_ruta: "006",
    tgl_masuk: new Date("2026-02-06T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Pasaman",
    nagari: "Aua Kuniang",
    sls: "07",
    kode_sls_subsls: "0702",
    nks: "407",
    nama_PML: "Galih Prasetyo",
    nama_PPL: "Indah Permata",
    no_ruta: "007",
    tgl_masuk: new Date("2026-02-07T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Koto Balingka",
    nagari: "Parit",
    sls: "08",
    kode_sls_subsls: "0802",
    nks: "408",
    nama_PML: "Haris Saputra",
    nama_PPL: "Julia Safitri",
    no_ruta: "008",
    tgl_masuk: new Date("2026-02-08T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Ranah Batahan",
    nagari: "Batahan",
    sls: "09",
    kode_sls_subsls: "0902",
    nks: "409",
    nama_PML: "Irfan Maulana",
    nama_PPL: "Kartini Putri",
    no_ruta: "009",
    tgl_masuk: new Date("2026-02-09T08:00:00.000Z"),
  },
  {
    provinsi: "Sumatera Barat",
    kabupaten: "Pasaman Barat",
    kecamatan: "Sungai Beremas",
    nagari: "Maligi",
    sls: "10",
    kode_sls_subsls: "1002",
    nks: "410",
    nama_PML: "Jefri Alamsyah",
    nama_PPL: "Lina Wati",
    no_ruta: "010",
    tgl_masuk: new Date("2026-02-10T08:00:00.000Z"),
  },
];
