export const DATA_AWAL_SLS = [
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "010",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI BEREMAS",
    namaNagari: "AIA BANGIH",
    kodeSls: "0001",
    kodeSubSls: "01",
    nks: "50001",
    namaSls: "JORONG PASAR MUARA",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "010",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI BEREMAS",
    namaNagari: "AIA BANGIH",
    kodeSls: "0004",
    kodeSubSls: "02",
    nks: "50013",
    namaSls: "JORONG PASAR BARU BARAT",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "010",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI BEREMAS",
    namaNagari: "AIA BANGIH",
    kodeSls: "0007",
    kodeSubSls: "02",
    nks: "50026",
    namaSls: "JORONG KAMPUNG PADANG SELATAN",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "010",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI BEREMAS",
    namaNagari: "AIA BANGIH",
    kodeSls: "0008",
    kodeSubSls: "06",
    nks: "50033",
    namaSls: "JORONG KAMPUNG PADANG UTARA",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "010",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI BEREMAS",
    namaNagari: "AIA BANGIH",
    kodeSls: "0011",
    kodeSubSls: "07",
    nks: "50053",
    namaSls: "JORONG SILAWAI TENGAH",
  },

  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "020",
    kodeNagari: "002",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "RANAH BATAHAN",
    namaNagari: "BATAHAN",
    kodeSls: "0001",
    kodeSubSls: "02",
    nks: "00013",
    namaSls: "JORONG SILAPING",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "020",
    kodeNagari: "005",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "RANAH BATAHAN",
    namaNagari: "BATAHAN TENGAH",
    kodeSls: "0005",
    kodeSubSls: "02",
    nks: "00051",
    namaSls: "JORONG SIMPANG TOLANG",
  },

  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "030",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "KOTO BALINGKA",
    namaNagari: "PARIK",
    kodeSls: "0001",
    kodeSubSls: "08",
    nks: "00083",
    namaSls: "JORONG PARIT",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "030",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "KOTO BALINGKA",
    namaNagari: "PARIK",
    kodeSls: "0002",
    kodeSubSls: "02",
    nks: "00087",
    namaSls: "JORONG SIGALANGAN",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "030",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "KOTO BALINGKA",
    namaNagari: "PARIK",
    kodeSls: "0003",
    kodeSubSls: "01",
    nks: "00089",
    namaSls: "JORONG PEMUKIMAN BARU I",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "030",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "KOTO BALINGKA",
    namaNagari: "PARIK",
    kodeSls: "0001",
    kodeSubSls: "06",
    nks: "00081",
    namaSls: "JORONG PARIT",
  },

  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "040",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI AUR",
    namaNagari: "SUNGAI AUA",
    kodeSls: "0003",
    kodeSubSls: "02",
    nks: "00176",
    namaSls: "JORONG BUKIT HARAPAN",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "040",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI AUR",
    namaNagari: "SUNGAI AUA",
    kodeSls: "0019",
    kodeSubSls: "03",
    nks: "00187",
    namaSls: "JORONG TANJUNG BABOLIK",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "040",
    kodeNagari: "002",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI AUR",
    namaNagari: "SELINGKA MUARO",
    kodeSls: "0006",
    kodeSubSls: "02",
    nks: "00202",
    namaSls: "JORONG SUNGAI AUR TENGAH",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "040",
    kodeNagari: "005",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "SUNGAI AUR",
    namaNagari: "KASIK PUTIH SUNGAI TANANG",
    kodeSls: "0002",
    kodeSubSls: "01",
    nks: "00233",
    namaSls: "JORONG SUNGAI TANANG",
  },

  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "050",
    kodeNagari: "001",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "LEMBAH MELINTANG",
    namaNagari: "UJUANG GADIANG",
    kodeSls: "0006",
    kodeSubSls: "02",
    nks: "50081",
    namaSls: "JORONG PASAR LAMA SATU",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "050",
    kodeNagari: "002",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "LEMBAH MELINTANG",
    namaNagari: "BRASTAGI UJUNG GADING",
    kodeSls: "0004",
    kodeSubSls: "01",
    nks: "50092",
    namaSls: "JORONG ULU BONDAR BRASTAGI",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "050",
    kodeNagari: "008",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "LEMBAH MELINTANG",
    namaNagari: "KUAMANG ALAI UJUNG GADING",
    kodeSls: "0001",
    kodeSubSls: "04",
    nks: "50107",
    namaSls: "JORONG KUAMANG",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "050",
    kodeNagari: "008",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "LEMBAH MELINTANG",
    namaNagari: "KUAMANG ALAI UJUNG GADING",
    kodeSls: "0004",
    kodeSubSls: "06",
    nks: "50121",
    namaSls: "JORONG KUAMANG TIMUR",
  },
  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "050",
    kodeNagari: "008",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "LEMBAH MELINTANG",
    namaNagari: "KUAMANG ALAI UJUNG GADING",
    kodeSls: "0005",
    kodeSubSls: "04",
    nks: "50125",
    namaSls: "JORONG LUBUK ALAI SELATAN",
  },

  {
    kodeProvinsi: "13",
    kodeKabupaten: "12",
    kodeKecamatan: "110",
    kodeNagari: "016",
    namaProvinsi: "SUMATERA BARAT",
    namaKabupaten: "PASAMAN BARAT",
    namaKecamatan: "KINALI",
    namaNagari: "LIMAU PURUIK",
    kodeSls: "0003",
    kodeSubSls: "02",
    nks: "00846",
    namaSls: "JORONG LIMAU PURUIK TIMUR",
  },
];
